language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

before_script:
  - phpenv config-rm xdebug.ini || true
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

matrix:
  allow_failures:
    - php: nightly
